---
abstract: 'restrict access to pages based on user accounts'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-UserLogin
provides:
  App::ZofCMS::Plugin::UserLogin:
    file: lib/App/ZofCMS/Plugin/UserLogin.pm
    version: 0.0212
requires:
  DBI: 1.602
  HTML::Template: 2.9
  URI::Escape: 3.29
resources:
  license: http://dev.perl.org/licenses/
version: 0.0212
